[package]
name = "mana"
description = "Ikozu's magic as a machine you can program: the machine, the world and the assembler"
version.workspace = true
edition.workspace = true

[dependencies]
indexmap = "2.14.2"
regex = "1.13.1"

[dev-dependencies]
serde_json = { version = "1", features = ["float_roundtrip"] }

[lints]
workspace = true
