// One line on each instruction and port, for the tester's reference and hover. SPEC §5 has the full story.

export type OpDoc = { syntax: string; group: string; doc: string; step?: string }

const d = (syntax: string, group: string, doc: string, step?: string): OpDoc => ({ syntax, group, doc, step })

export const OP_DOCS: Record<string, OpDoc> = {
  NOP: d('NOP', 'control', 'Nothing.'),
  HALT: d('HALT', 'control', 'The spell ends. Its result is the weave in n0, if any.'),
  FAIL: d('FAIL #code', 'control', 'The spell ends, failed, with a code.'),
  TICK: d('TICK', 'control', "End this tick's thinking."),
  RET: d('RET', 'control', 'Return from a CALL. In an order, the cell is done for this tick.'),
  JMP: d('JMP L', 'control', 'Jump.'),
  JEQ: d('JEQ L', 'control', 'Jump if the last CMP was equal.'),
  JNE: d('JNE L', 'control', 'Jump if the last CMP was not equal.'),
  JLT: d('JLT L', 'control', 'Jump if the last CMP was less.'),
  JLE: d('JLE L', 'control', 'Jump if the last CMP was less or equal.'),
  JGT: d('JGT L', 'control', 'Jump if the last CMP was greater.'),
  JGE: d('JGE L', 'control', 'Jump if the last CMP was greater or equal.'),
  CALL: d('CALL L', 'control', 'Call a routine. n0–n15 are its to use; n16–n31 are kept for the caller.'),

  LDI: d('LDI d, #imm', 'numbers', 'd = imm'),
  MOV: d('MOV d, s', 'numbers', 'd = s. Numbers only: no instruction copies mana.'),
  ADD: d('ADD d, s', 'numbers', 'd = d + s'),
  SUB: d('SUB d, s', 'numbers', 'd = d − s'),
  MUL: d('MUL d, s', 'numbers', 'd = d × s'),
  DIV: d('DIV d, s', 'numbers', 'd = d ÷ s. Dividing by 0 gives 0. Slow.'),
  MOD: d('MOD d, s', 'numbers', 'd = d mod s. Slow.'),
  NEG: d('NEG d', 'numbers', 'd = −d'),
  ABS: d('ABS d', 'numbers', 'd = |d|'),
  SQRT: d('SQRT d', 'numbers', 'd = √d (0 below 0). Slow.'),
  FLOOR: d('FLOOR d', 'numbers', 'Round d down.'),
  ROUND: d('ROUND d', 'numbers', 'Round d to the nearest whole number.'),
  SIN: d('SIN d', 'numbers', 'd = sin d, in radians. Very slow.'),
  COS: d('COS d', 'numbers', 'd = cos d, in radians. Very slow.'),
  TAN: d('TAN d', 'numbers', 'd = tan d, in radians. Very slow.'),
  ATAN: d('ATAN d', 'numbers', 'd = atan d. Very slow.'),
  ATN2: d('ATN2 d, s', 'numbers', 'd = atan2(d, s): the angle of the point (s, d). Very slow.'),
  MIN: d('MIN d, s', 'numbers', 'd = min(d, s)'),
  MAX: d('MAX d, s', 'numbers', 'd = max(d, s)'),
  CMP: d('CMP a, s', 'numbers', 'Compare a with s, for the jumps.'),
  PUSH: d('PUSH n', 'numbers', "Push n on the mind's stack."),
  POP: d('POP n', 'numbers', "Pop the mind's stack into n."),
  LD: d('LD d, [n]', 'numbers', "d = memory[n]. The mind's memory holds up to 256 numbers."),
  ST: d('ST s, [n]', 'numbers', 'memory[n] = s'),
  IN: d('IN d, PORT', 'numbers', 'Read a port: the will, the senses, the world. Size-3 ports fill a triple.'),

  GATH: d('GATH m, s', 'body', 'Draw s M of air mana from around the body into m, raw. Less if the air is thin.', 'GATHER'),
  CIRC: d('CIRC m', 'body', 'Hold m for `focus` ticks. Unheld mana slips into the body’s flow.', 'CIRCULATE'),
  FILT: d('FILT md, ms, s', 'body', 'Move part s (0–3) of ms into md, times your affinity for it. The rest of that part slips into the flow.', 'FILTER'),
  SPLT: d('SPLT md, ms, s', 'body', 'Move s M of ms into md, keeping its proportions.'),
  JOIN: d('JOIN md, ms', 'body', 'Move all of ms into md.'),
  MEAS: d('MEAS d, m', 'body', 'd = how much m holds.'),
  PART: d('PART d, m, s', 'body', 'd = how much of part s m holds.'),
  VENT: d('VENT m', 'body', 'Let all of m out, gently, around the body.'),

  PROB: d('PROB d, n:3, s', 'reach', 'd = how much matter of part s is in the cell at n:3.', 'PROBE'),
  AIRM: d('AIRM d, n:3, s', 'reach', 'd = how much air mana of part s floats at n:3.', 'PROBE'),
  SEND: d('SEND m, n, n:3, n:3', 'reach', 'Let n M of m out loose, at a position, with a velocity.', 'SEND'),

  WEAV: d('WEAV d, n:3', 'weave', 'Begin a weave, in hand, with its origin at n:3. Its id goes into d.'),
  TURN: d('TURN w, n:3', 'weave', "Turn the weave's frame so forward points along n:3, about the vertical.", 'POSITION'),
  EMIT: d('EMIT m, n, w, n:3', 'weave', "Move n M of m into the weave, at n:3 in the weave's frame."),
  WSET: d('WSET w, #k, s', 'weave', "Write the weave's register wk."),
  WGET: d('WGET d, w, #k', 'weave', "Read the weave's register wk."),
  ORDR: d('ORDR w, L', 'weave', 'Give the weave its order: the routine at L, run by every cell, every tick.', 'ORDER'),
  MANI: d('MANI w', 'weave', 'Set the weave loose. It leaves the body and starts running its order.', 'SEND'),
  LOCK: d('LOCK w, SHAPE|INPUT|ORDER', 'weave', 'Lock its shape, its input or its order. Only after MANI.', 'LOCK'),
  RELS: d('RELS w', 'weave', 'Let the weave go: its mana goes loose where it is.'),

  MOVE: d('MOVE n:3', 'order', "Move this cell by n:3 this tick, in the weave's frame, with the matter it binds."),
  TUCH: d('TUCH d', 'order', "d = 1 if this cell is against matter or a body that isn't its own or its maker's."),
  GETW: d('GETW d, #k', 'order', "Read this weave's register wk."),
  PUTW: d('PUTW #k, s', 'order', "Write this weave's register wk, from the next tick."),
  DISS: d('DISS', 'order', 'The whole weave comes apart. Its mana goes loose where it is.'),
  CNDS: d('CNDS s', 'order', "Condense s M of this cell's free mana into matter of the same parts, as much as the cell has room for."),
}

export const PORT_DOCS: Record<string, string> = {
  AIM: 'Where the caster means it to go (3).',
  HAND: 'The casting hand (3).',
  SELF: "The caster's body (3).",
  AMOUNT: 'How much the caster means to gather.',
  FORCE: 'How hard.',
  MAINTAIN: '1 while the caster keeps the spell going.',
  CELL: "The world's cell size, in metres.",
  DEPTH: "The world's depth in cells: 1 in 2D.",
  LOAD: "The body's load now.",
  CAPACITY: "The body's capacity.",
  ORIGIN: "In an order: where the weave's origin is now (3).",
  MAKER: "In an order: where the weave's caster is now (3).",
}
